### ISSUE TITLE
Error on install - "Failed at the sharp@0.18.4 install script"

### ISSUE THREAD

**Issue by JayHoltslander** [zouhir/lqip-cli#3]
* MacOS v10.14.6
* npm v6.12.1

````
$ npm i -g lqip-cli
/usr/local/bin/lqip -> /usr/local/lib/node_modules/lqip-cli/index.js
/usr/local/bin/lqip-cli -> /usr/local/lib/node_modules/lqip-cli/index.js

> sharp@0.18.4 install /usr/local/lib/node_modules/lqip-cli/node_modules/sharp
> node-gyp rebuild

/bin/sh: /usr/local/bin/brew: /bin/bash: bad interpreter: Permission denied
gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR || true' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/lqip-cli/node_modules/sharp
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jholtslander/.npm/_logs/2019-12-16T22_29_22_760Z-debug.log
Fenlon:folder jholtslander$ node-gyp rebuild
-bash: node-gyp: command not found
````

**Comment by samholton** [comment]
Created https://github.com/samholton/lqip-gen
